# Config to extract SALSA-Lite or SALSA-IPD feature for TAU-NIGENS Spatial Sound Events (TNSSE) 2021 dataset
data_dir: 'dataset/data'
feature_dir: 'dataset/features'
data:
  format: 'mic'
  fs: 24000
  n_fft: 512
  win_len: 512
  hop_len: 300  # 300 for 12.5ms for n_fft = 512; 150 for n_fft = 256
  fmin_doa: 50  # Hz
  fmax_doa: 2000 # Hz
